services:
    mesd.doctrine.filter.configurator:
        class: Mesd\OrmSecurityFilterBundle\Filter\Configurator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.context"
        tags:
            - { name: kernel.event_listener, event: kernel.request }